version: '3'
services:
  nginx:
    build: 
      context: ../../
      dockerfile: ./dockers/prod/images/nginx/Dockerfile
    ports:
      - ${WEB_PORTS:-80:80}
    networks:
      - backend-network
    depends_on:
      - postgres
      - api

  api:
    build: 
      context: ../../
      dockerfile: ./dockers/prod/images/php/Dockerfile
    networks:
      - backend-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    ports:
      - ${POSTGRES_PORTS:-5432:5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 

volumes:
  postgres_data: